### ISSUE TITLE
Sectors list view

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#134]
There needs to be a way to discover sectors of a project that have never been successfully synced. Maybe in a generic list of all sectors that can be filtered by various options just like datasets?
Consider:
 - last sync status
 - last sync date
 - synced records
 - dataset
 - rank

**Comment by mdoering** [comment]
The response could be a list of sectors with the last SectorImport metrics attached (or both rather in a new object to avoid messing up the Sector class).

**Comment by mdoering** [comment]
I would imagine a pageable list of all sectors with their dataset, subject, target and last sync status & date would be useful. Optionally filtered by:
 - dataset
 - a date to show only sectors that have not been synced since that day
 - broken sectors
 - higher taxon filter, e.g. show only sectors under Tracheophyta

**Comment by thomasstjerne** [comment]
I guess the API for this is partly in place and at least it has the following options for params:
`broken=true/false` `datasetKey=` and `sourceDatasetKey`
Are there currently any more search or sort options? thinking of `targetName`  and `subjectName` mostly

**Comment by mdoering** [comment]
No, the API needs to be done still. Is the above a good starting point to implement?

Add a search on target and/or subject matching the full word or probably better just the start of it sounds useful to me.
