### ISSUE TITLE
use keys to select dropdowns

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#188]
E.g. when adding a new taxon in the tree selecting the rank by scrolling down the list is cumbersome. Allow to use first letters using the keyboard to select values

**Comment by mdoering** [comment]
This is not working for me and really slowing down editing

**Comment by mdoering** [comment]
It should work in any form. Decisions, new taxa, estimates, dataset metadata etc.

**Comment by thomasstjerne** [comment]
> This is not working for me and really slowing down editing

It works in most places, if you find a specific place where it has not been fixed, please point me to that exact place

**Comment by mdoering** [comment]
works in name search form indeed!
Its odd, if I open the drop downs I can select options via keys. But if I just use tab to switch the forms the keys do not open up the drop down. You can only open them by clicking or using the arrow keys. For example in the metadata form on dev:
https://data.dev.catalogue.life/dataset/3/meta

**Comment by thomasstjerne** [comment]
When you tab into a select, it can be opened by arrow down key and then you can use keys to search. This is the default behaviour of the the selects from the UI lib I am using.  It would be rather time consuming to replace those with something else throughout the code or add custom onFocus code to all of them.

**Comment by mdoering** [comment]
ok, too bad. But now I know it works with one extra arrow key its not so bad anymore. At least one can use only the keyboard and does not have to resort to the mouse.
