### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#295]
@yroskov and I understand that it's challenging to do in the REST framework, but not applying decisions to all paginated pages will likely result in bugs being introduced into the data, which occurred recently with Scarabs. Yuri had blocked a bunch of names with pagination set to 500 duplicates per page, and later decided it was a mistake to block those names, so he went back to undo it, but forgot that the pagination defaults back to 50 duplicates per page so he applied the accepted name decision (to reverse the block decision) to the first page, which left 450 duplicates still blocked.

Once we start getting more clearinghouse users, I'd predict that these data bugs caused by pagination will become a common problem because I think most users will assume that they are applying decisions to all pages. If someone interrupts a user while they are in the middle of applying decisions page-by-page they might forget to finish.

@thomasstjerne, maybe the frontend could do this by remembering the user's check-all action, requesting the next page, applying the remembered check-all action, and continuing to do that until the decision is applied to all checked records on all pages? Similarly if the user browses to the next page, the check-all action could be remembered and applied to the view. This will still potentially create complications if the user unchecks some boxes, but if the frontend remembers the checked box IDs for each viewed page, it might still be possible to do it?

**Comment by gdower** [comment]
It might simplify development if the pagination default is set to 500 records per page, and no other pagination settings are offered. Otherwise, if the user changes the pagination setting, the setting should be remembered with a cookie or by updating a user-specific configuration.

**Comment by mdoering** [comment]
I would prefer a client state to remember the page size - 500 is too much for a general default.

I think the main reason why we did not want to apply a decision to all pages was that these are not reviewed and you apply a decision to unseen data. I dont think this is strictly a technical one

**Comment by thomasstjerne** [comment]
The chosen pagesize will now be remembered.

> maybe the frontend could do this by remembering the user's check-all action, requesting the next page, applying the remembered check-all action, and continuing to do that until the decision is applied to all checked records on all pages?

If we decide that decisions should be auto-applied to unseen data, I think the backend should allow for posting a predicate and a decision to apply for all names matching the predicate. We should not rely on the frontend for handling this logic.

**Comment by mdoering** [comment]
Yes I agree. That was my original plan but I recall we decided against this in one of our demos. @yroskov @gdower what is your preference?

**Comment by gdower** [comment]
If @yroskov were doing this in a spreadsheet, for some types of duplicates decisions he would apply the default decision to all names by drag and drop, and then he would manually scrutinize the names, changing the decision as needed. The records are still going to get scrutinized and initially it's going to be a really heavy workload so making the process as frictionless as possible is important.

Yuri also raised the point that sometimes he starts work in the office and continues work at home, which might cause the same type of data bug where he forgets and assumes pagination is set to 500 when it's set to 50. Pagination settings should probably be stored as a user configuration in the backend instead of a client state. Probably this should go in Phase II though, as other things are higher priority. @mdoering, I can open a backend issue on this for consideration and later implementation if you'd like.

**Comment by mdoering** [comment]
We can and should persist the user configs from the client in user preferences in the backend already. @thomasstjerne is this already being done? But otherwise the backend is and should be stateless.

**Comment by mdoering** [comment]
Ouch no, there is no update settings resource exposed. I will add one now

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/30f8565bb5076dd0c270dc7ad853d039c67516a9#diff-77cf813693b4e0b43c2ade96ad0ab12b
