### ISSUE TITLE
Sync diff difficult to use

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#320]
The sync diff form is difficult to use:
https://www.col.plus/assembly/3/sync/6238/diff?attempts=1..2

The dropdowns should get a label so you know what they are about.
When selecting "Attempt 0" is also places "undefined" into the URL. Is there ever an attempt 0?

A heading would also be good so you know what this page does, especially if the diff is empty so both attempts are the same. This should be explicitly be mentioned.

**Comment by mdoering** [comment]
Empty diffs for syncs that havent changed show basically a blank page:

<img width="1087" alt="Screenshot 2019-12-02 at 12 11 04" src="https://user-images.githubusercontent.com/327505/69954993-fa303980-14fc-11ea-8625-038f51967adf.png">

**Comment by mdoering** [comment]
The first attempt is always 1, never zero

**Comment by thomasstjerne** [comment]
The response is currently always empty.

This one should show a diff: https://api.dev.catalogue.life/sector/20002/treediff?attempts=1..2

See  https://github.com/Sp2000/colplus-backend/issues/384

**Comment by thomasstjerne** [comment]
Depending on https://github.com/CatalogueOfLife/backend/issues/384
