### ISSUE TITLE
Blank message displayed on stop sync

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#342]
As described in [Sp2000/colplus-backend#468](https://github.com/Sp2000/colplus-backend/issues/468), the frontend gives a blank message when trying to cancel these syncs:

![image](https://user-images.githubusercontent.com/8573609/64626084-de604000-d3b2-11e9-8dfa-1e9f0a36ae11.png)

@mdoering, the frontend seems to send the correct response to delete a sector sync, so probably the failure to delete is actually a backend bug:

```
https://api.col.plus/assembly/3/sync/2729
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer [redacted]
Origin: https://www.col.plus
DNT: 1
Connection: keep-alive
Referer: https://www.col.plus/
DELETE: HTTP/1.1 204 No Content
Date: Tue, 10 Sep 2019 15:41:17 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Keep-Alive: timeout=5, max=72
Connection: Keep-Alive
```

Frontend version: 5e066ea September 10, 2019 8:46 AM
Backend version: 530045e September 9, 2019 11:45 AM

**Comment by mdoering** [comment]
I encountered the same thing earlier today.
I tried to sync a sector, it hang in the prepare phase, not showing in the assembly state at all.
I synced once more and got two of those ghosts. I then restarted the application and it was still the same. I then tried to delete the sector with no luck. I then deleted the whole subtree and the assembly tree didnt show the deletion, but it ultimately was then removed together with the sector and its ghost imports.
