### ISSUE TITLE
Block taxon in assembly source giving 500 & 400 errors

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#346]
Yesterday we hit a 500 error when trying to block a taxon in the assembly source, then a 400 error:

In an attempt to fix the broken Tettigonia sector, we used the block taxon button in the source frame of Assembly for the family Cicadidae:

![image](https://user-images.githubusercontent.com/8573609/64990155-d7df3600-d894-11e9-9726-4984dda1107d.png)

We got a 500 error and then 400 error the 2nd time while trying to snapshot the error:

![image](https://user-images.githubusercontent.com/8573609/64990376-5045f700-d895-11e9-9eee-90c33741dc11.png)

These errors occurred around that time frame, although I'm not sure if these are the 400 and 500 errors we got: [1](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW07ucNfHCKcR6PFPGe5?_a=(columns:!(_source),filters:!())) and [2](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW07ufVVHCKcR6PFPGfq?_a=(columns:!(_source),filters:!())).

Full steps to reproduce are available [here](https://github.com/Sp2000/colplus-repo/issues/65#issuecomment-531957528).

We were running versions:

Frontend version: 6cecadb September 12, 2019 4:43 AM
Backend version: eaf65f9 September 16, 2019 11:02 AM

**Comment by gdower** [comment]
This might have been caused by the [ES running out of disk space issue](https://github.com/Sp2000/colplus-backend/issues/479).

**Comment by gdower** [comment]
Here's the [full list of errors that occurred](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-16T17:00:00.000Z',mode:absolute,to:'2019-09-16T21:30:59.999Z'))&_a=(columns:!(level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!f,type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

**Comment by gdower** [comment]
Okay, I found the actual [500](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-16T17:00:00.000Z',mode:absolute,to:'2019-09-16T23:30:59.999Z'))&_a=(columns:!(_source),filters:!(),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(query:'%22HTTP%5C%2F1.1%5C%22%20500%22')),sort:!('@timestamp',desc))) and [400](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-16T17:00:00.000Z',mode:absolute,to:'2019-09-16T23:30:59.999Z'))&_a=(columns:!(_source),filters:!(),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(query:'%22HTTP%5C%2F1.1%5C%22%20400%22')),sort:!('@timestamp',desc))) errors, which were logged at the INFO level. Unfortunately, it doesn't look like it gives the request body though.

**Comment by gdower** [comment]
I captured output from the block taxon button repeating the same steps as before:

```

https://api.col.plus/decision
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer [redacted]
Content-Type: application/json;charset=utf-8
Content-Length: 86
Origin: https://www.col.plus
DNT: 1
Connection: keep-alive
Referer: https://www.col.plus/
{"datasetKey":1189,"subject":{"id":"xa68z","name":"<i>Tettigonia</i>"},"mode":"block"}
POST: HTTP/1.1 201 Created
Date: Tue, 17 Sep 2019 18:59:25 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Content-Type: application/json
Location: http://api.col.plus/decision/1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 1
Keep-Alive: timeout=5, max=27
Connection: Keep-Alive
```

**Comment by mdoering** [comment]
@thomasstjerne please do not post names with markup like `<i>Tettigonia</i>` into the decision API. We could consider to load some data in the backend based on just the id, but that would require to define a base set of attributes to load, e.g. name, rank, authorship & status? It might actually be the cause of the blocking to not be effective when we do a rematch, but not sure. Otherwise the creation of the decision looks correct and returns a correct 201.

You can then always check the created decision object with the Location given, in this case:
http://api.col.plus/decision/1

**Comment by thomasstjerne** [comment]
@gdower and @yroskov is this still reproducable?
