### ISSUE TITLE
Fuse workbench and name search?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#353]
The workbench needs all search options that the regular name search has already, e.g. free text search, filter by name type, rank, issues, etc.

The only real difference is that the workbench allows to manage decisions for the resulting records. How about a single search with a single set of filters but the option to turn on/off the management of decisions? That would basically change how results are presented and if with/without decision setting is visible?

**Comment by gdower** [comment]
@yroskov and I agree with this.

**Comment by thomasstjerne** [comment]
This has been superseeded by the new menu structure.
