### ISSUE TITLE
Restoring the classification tree state on browser back button click

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#398]
I realize it's likely challenging to implement, but [a new user provided feedback](https://github.com/Sp2000/colplus-repo/issues/76) that they would like the [classification tree](https://dev.col.plus/dataset/2061/classification) to be expanded back to it's previous state when they click the browser back button after viewing a taxon page.

I could foresee cases where a user might want to check something on the taxon page and then hit the back button and are frustrated that they have to manually re-expand the tree back to the previous state in order to continue working with the contextual classification information that they needed. It could get really tedious if they have to do that multiple times. Maybe as a temporary fix, clicking on a name in the classification tree should default to opening in a new tab? @yroskov, what do you think?

The sourceTaxonKey is a big improvement over what we had before, but if multiple taxa were expanded at a higher level, they are not re-expanded. Maybe sourceTaxonKey could be an array of sourceTaxonKeys that are expanded? If that change needs the API we should defer this until phase 2.

**Comment by thomasstjerne** [comment]
I dont think this will be possible. But of course we could open taxon pages in a new tab

**Comment by yroskov** [comment]
tree opened in a new tab is better then nothing

**Comment by mdoering** [comment]
With the option to open in a new tab and very soon to [open a taxon in the tree from a details page](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/743) I think we can close this issue. Keeping state of the tree with all its opened branches is hugely stateful which we should avoid.
