### ISSUE TITLE
Auto-complete assembly search bug

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#438]
@yroskov found an assembly auto-complete suggestion search bug where suggest displays higher taxa uninomials when the user backspaces. When the user types something else into assembly search after backspacing, the higher taxa uninomials do not disappear even though they are not a good search suggestion.

To reproduce:

1) Go to https://data.catalogue.life/assembly
2) In the assembly search type in "Trifo"
3) Hit backspace until you have nothing: ""
4) Search for "Trifo" (or anything)
5) Animalia will be stuck at the top even though it's not a good search match:

![image](https://user-images.githubusercontent.com/8573609/70074355-2791eb80-15c0-11ea-9501-4efb54364d42.png)

Frontend version: ac84abb November 28, 2019 3:39 AM
Backend version: 2d2881c November 26, 2019 5:56 AM

**Comment by thomasstjerne** [comment]
Cant reproduce, please re-open if you still see this error.
