### ISSUE TITLE
dataset link broken

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#451]
I cannot open a simple dataset link anymore, only from within the app but not starting the application with https://data.catalogue.life/dataset/1006

**Comment by thomasstjerne** [comment]
Currently everything is catalogue scoped so the dataset link only exists in the context of a catalogue: https://data.catalogue.life/catalogue/3/dataset/1006

**Comment by thomasstjerne** [comment]
Duplicate of https://github.com/CatalogueOfLife/clearinghouse-ui/issues/460
