### ISSUE TITLE
consider alternatives to catalogue scoped path

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#460]
Having the catalogue scope in the path seems wrong to me.
The UI should probably follow the API resources as much as possible.

Could the catalogue context not also be given as a query parameter or even a client session?

**Comment by thomasstjerne** [comment]
I am considering to move everything that relates directly to both a catalogue AND and a dataset to the catalogue section of the UI.

This would be:
1. Tasks
2. Duplicates
3. Workbench

Then it would be easier to get rid of the catalogue path param in the dataset section.
Other implications:
1. Dataset sectors would show all sectors from all catalogues it contributes to. The UI would then have a filter to scope only by a selected catalogue. An url param `catalogueKey` could be used for  linking / default value

**Comment by mdoering** [comment]
That sounds reasonable to me. Moving taska, duplicates and workbench under a project makes things cleaner I thinkg. A `catalogueKey` or maybe already `projectKey` http parameter for filtering sectors and generally assigning the project scope would be my favorite.

Tasks clearly only belong to a project, not to the dataset itself. The workbench
 (maybe we should simply call that "decisions"?) appears to be the same as the regular search, just with the option to apply decisions. So on the plain dataset scope (where dataset owner and the general public will look) the same functionality is already provided by the name search.

For duplicates I am slightly less certain. It is very valuable for dataset owners to look for issues and duplicates. But they would never assign decisions of any kind. Maybe we can have duplicates in both parts, but only manage decisions under the project?

We also need to differ between authorized editors and anonymous users - the later should still be able to view existing decisions under a project (workbench), just have no options to modify them.
