### ISSUE TITLE
Brainstorm on project-oriented frontend design

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#465]
@yroskov and I started brainstorming on how to re-arrange the existing frontend components into a more project-oriented architecture, where users could register a project and use the assembly tools to create their own catalogues, or fork an existing project like CoL and apply their own project-specific decisions that they would need in order to use CoL (or another project) as their project's taxonomic backbone. 

I'm opening a ticket on this just so that we remember to continue collaborating on it in Phase II of the project. Please contribute to the brainstorm document instead of commenting in this thread.

https://docs.google.com/document/d/1LtonD96ucc-6m2FNkt7p0A79uJFiSPx0jWawSsFyxCQ/edit#

**Comment by gdower** [comment]
@ayco-at-naturalis, I fixed the permissions issue with the Google link.

**Comment by mdoering** [comment]
See also https://github.com/Sp2000/colplus/blob/master/docs/projects.md
