### ISSUE TITLE
Reduce unused space next to logo in dataset metadata

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#489]
There is lot of unused blank space next to the logo in the metadata view which we should make use of, especially if there is no logo existing yet.

Suggest to move alias and other properties which usually contain short values to the top floating around the logo. Keep description below as its often longer text.

<img width="1481" alt="Screenshot 2020-02-12 at 07 30 19" src="https://user-images.githubusercontent.com/327505/74309007-fa08b180-4d69-11ea-8aae-06c9bf38e385.png">

**Comment by thomasstjerne** [comment]
The upload element, delete and import buttons are only visible to editors, admins. Anonymous users, and users without roles will not see this.
I´d rather not operate with two different renderings of all the rows, but keep them as is, inserting the authorized bits above the rows.

**Comment by thomasstjerne** [comment]
<img width="1374" alt="Screenshot at Oct 14 10-42-50" src="https://user-images.githubusercontent.com/1666484/95965311-0ddd4980-0e0a-11eb-9589-1f617513f6b7.png">
