### ISSUE TITLE
rematch sectors reports error but worked

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#490]
When matching a broken sector in a datasets sector view the UI shows "" but in fact the matching worked fine if you reload the page.

<img width="1196" alt="Screenshot 2020-02-19 at 10 22 13" src="https://user-images.githubusercontent.com/327505/74820135-c5649f00-5301-11ea-8155-fb46419957bd.png">

**Comment by thomasstjerne** [comment]
How should I determine if it worked?
Currently, the criteria is that after rematch the sector must have both subject and target:
`                    const success = _.get(sector, 'data.target.id') && _.get(sector, 'data.subject.id');
`

**Comment by mdoering** [comment]
Good question. The `POST /assembly/{key}/rematch` resource does not return the matched sector. The same resource can be used to rematch a decision, sector, entire dataset or all decisions and sectors. 

Should we maybe just return a boolean with true for success?
If you'd reload the sector you should be able to see the new ids and your comparison above seems fine.

**Comment by mdoering** [comment]
Well, as we potentially deal with many subjects to be rematched (e.g. entire dataset) now the following is returned. Maybe we should keep it like this:

```
{
    "sectors": {
        "broken": 0,
        "updated": 1,
        "unchanged": 0,
        "total": 1
    },
    "decisions": {
        "broken": 0,
        "updated": 0,
        "unchanged": 0,
        "total": 0
    },
    "estimates": {
        "broken": 0,
        "updated": 0,
        "unchanged": 0,
        "total": 0
    },
    "datasets": 0
}
```

**Comment by thomasstjerne** [comment]
So the sector it self is not in the response anymore? Then I have to rewrite the frontend code to adapt.

**Comment by mdoering** [comment]
Not sure if that ever was the response, at least not for a long time.
A single request can match potentially thousands of sectors. We could return all these sectors, but I doubt its a good idea. Or should we?

**Comment by thomasstjerne** [comment]
The buttons in the table posts a single sector:
`{sectorKey: record.key}`

I think it used to simply return the sector, and if it - after rematch - had a target, then it would assert it was a success.
