### ISSUE TITLE
managed dataset sectors

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#500]
if you look at the sectors menu item for managed datasets / catalogues instead of source datasets nothing is shown: https://data.catalogue.life/catalogue/3/dataset/3/sectors

We should list all sectors or even better a sector overview grouped by datasets maybe?

**Comment by thomasstjerne** [comment]
I guess only if the selected catalogueKey === datasetKey, i.e. not looking at the dataset as source for another catalogue.

**Comment by mdoering** [comment]
Yes!

**Comment by mdoering** [comment]
As managed datasets can also be the source of a sector this should probably be empty and not show sectors which have a target in the currently selected dataset. Better keep things as they are
