### ISSUE TITLE
Create scientificName & authorship duplicate view

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#508]
subspecies are shown as species - subspecific epithet is missing but rank given

<img width="1775" alt="Screenshot 2020-03-04 at 22 06 46" src="https://user-images.githubusercontent.com/327505/75873725-889db980-5e64-11ea-8ef9-51fcbab29615.png">

**Comment by thomasstjerne** [comment]
On the screenshot no name category is selected
When there is no Col check or name category selected, the duplicate page currently defaults to binomial. If it makes sense, I will change this to trinomial - but this will most often result in empty columns.

**Comment by mdoering** [comment]
trinomial would also have problems with showing uninomials.
I think there should be a 4th view just showing scientificName and authorship without any of the parsed atoms. And this view should be the default if uni/bi/tri nomial is not selected.

Its also the only way to show unparsed names like viruses etc

**Comment by mdoering** [comment]
This exists already with the "Show atomized names" flag
