### ISSUE TITLE
Add autocompletion to meta data selects

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#514]
e.g. dataset metadata

**Comment by thomasstjerne** [comment]
All selects work fine in Chrome Version 80.0.3987.149 (Official Build) (64-bit).

Can you provide some browser details, and maybe also point towards one specific select that doesn´t work (I just tested all the meta data ones)

**Comment by mdoering** [comment]
it does not work on both chrome (Version 80.0.3987.149 (Official Build) (64-bit)) and Safari on Mac. The drop downs do work manually with the mouse, but you cannot select values using keyboard values, e.g. press `c` in the data format to select ColDP:

https://data.catalogue.life/dataset/2098/meta

**Comment by thomasstjerne** [comment]
Got it. Thought you meant arrow key navigation and select by hitting enter, which works fine.
