### ISSUE TITLE
Cannot attach "Not assigned" groups in assembly

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#518]
@yroskov [found that "Not assigned" groups cannot be attached in assembly](https://github.com/CatalogueOfLife/data/issues/114#issuecomment-603322952). To reproduce, try to drag and drop the not assigned group [here](https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=7924e657-7fcf-4dfb-a394-68a4a62d71c8&datasetKey=2073&sourceTaxonKey=x7QG) onto Kingdom Fungi and you'll get the notice, "Only one sector can be configured for each taxon. Not assigned -> Fungi is already defined as a sector ":

![image](https://user-images.githubusercontent.com/8573609/77448870-4b6f7c00-6dbf-11ea-9031-5c7565145afa.png)

As a workaround, we can [directly attach the family Clavariaceae to Fungi](https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=7924e657-7fcf-4dfb-a394-68a4a62d71c8&datasetKey=2073&sourceTaxonKey=xLEN), but some "Not assigned" groups have lots of sub-groups (e.g., [the 31 genera here that have "Not assigned" as their family](https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=7924e657-7fcf-4dfb-a394-68a4a62d71c8&datasetKey=2073&sourceTaxonKey=x7QN)) and if we manually register all of those as sectors if additional sub-groups are added in the future those sectors probably won't be automatically registered and then would not be included in the Catalogue without manual intervention.

If you try to drag a "Not assigned" group onto "Not assigned" in assembly, you get the error, "You cannot create sectors on placeholder nodes." You can try to reproduce that [here](https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=7924e657-7fcf-4dfb-a394-68a4a62d71c8--incertae-sedis--FAMILY&datasetKey=2073&sourceTaxonKey=x7QN) by dragging the "Not assigned" family onto the "Not assigned" family in assembly **after directly attaching the family Clavariaceae to Fungi (I deleted the sector).**

![image](https://user-images.githubusercontent.com/8573609/77450172-eddc2f00-6dc0-11ea-8ef7-a6632119c5ce.png)

**Comment by gdower** [comment]
@thomasstjerne, if any of this is unclear we could do a demo on our call on Thursday.

**Comment by mdoering** [comment]
It is not really a bug, not assigned groups do not exist as they are virtual placeholders created on the fly just to group subtaxa nicely in the tree. 

We could try to support them in the backend, but I would not be surprised if its non trivial.

A different solution could be to make the next higher taxon the sector and exclude/block other siblings if there are not too many? In this case it would mean to make SF the Fungi sector on kingdom level. Maybe that isn't such a bad idea? We can always block out certain parts and use different sources inside the sector

**Comment by yroskov** [comment]
Single sector SpFung - Fungi might be a solution in this case. I'll re-do this workbench.

**Comment by mdoering** [comment]
Is the purpose of this still open issue to support virtual "not assigned" groups as sectors? If so its primarily a backend problem - and one we cannot easily solve. 

Another option for the frontend could be to assist the user in creating sectors for all included taxa when the not assigned is dragged.

**Comment by gdower** [comment]
I re-opened it because we're still working on the issue. In my opinion, it's a usability issue because most people would probably expect being able to register sectors by dragging and dropping the "Not assigned" groups just as they would any other named group.

Your second point is what I was originally thinking, if it's possible. :+1:

**Comment by mdoering** [comment]
@thomasstjerne lets create a sector for each direct child of unassigned nodes.

**Comment by gdower** [comment]
This could be low priority, although "Not assigned" groups are pretty common. Your [above workaround](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/518#issuecomment-603390060) probably will work in this case. I'm running conversion on it now.

**Comment by mdoering** [comment]
@thomasstjerne a sector in the API now has a new property `placeholderRank` that should only be populated for unassigned placeholders. If placeholderRank is family, only diret children of ranks below family are included in the sync.

Note that the synced taxa all have the same sectorKey and we should probably place the sectorKey also on the virtual unassigned node for better visualisation - that is not done by the backend and Im not sure if thats gonna be easy. Visualisation of the sector on both source and target is challenging I bet.

**Comment by mdoering** [comment]
@thomasstjerne I think I should actually handle everything in the backend.
Just create sectors like normal without the placeholderRank, but use the virtual nodes id which contains the rank. The backend then knows how to treat it and parse out the rank just like we do in the tree API. Similar the tree API will have to figure out to create sectors for the virtual unassigned nodes. So nothing really for the frontend to worry about. Just allow unassigned nodes to be dragged

**Comment by mdoering** [comment]
@thomasstjerne there is 404 error when creating an unassigned sector:

<img width="706" alt="Screenshot 2020-03-30 at 16 27 35" src="https://user-images.githubusercontent.com/327505/77924058-8253ff00-72a3-11ea-8741-da19b9d8055b.png">

What is that call for? Only the tree and sector API know about the virtual nodes.

**Comment by thomasstjerne** [comment]
It is because not all necessary data is in the tree API. When an attachment is done, both source and target are fetched from the taxon API to get 

1. the unformatted taxon name
2. the status.

I can make a check and dismiss the call for placeholders?
Otherwise both the unformatted name and the status should be included in the tree API. Then the frontend code could be further simplified, avoiding those calls

**Comment by mdoering** [comment]
dismiss the call for placeholders for now if thats not very intrusive.

But lets plan to add the missing bits to the TreeAPI then!
Do you need both the formatted and unformatted name? Maybe a method to strip of the html tags is enough to get the unformatted name from the marked up one?

**Comment by mdoering** [comment]
The Tree API now returns name, authorship and formattedName. Status was there already. The extra taxon call should be obsolete now.

sectorKey can also be populated in placeholder nodes now

**Comment by mdoering** [comment]
@thomasstjerne Checks for an existing duplicate name "Not assigned" probably do not make much sense in these cases:

<img width="1179" alt="Screenshot 2020-04-03 at 00 19 06" src="https://user-images.githubusercontent.com/327505/78305523-5eade480-7541-11ea-8dbe-386311fa19f4.png">

**Comment by mdoering** [comment]
Please make sure all sectors created from placeholder nodes use the sector mode UNION and never ATTACH. Syncs wont work as expected otherwise.

**Comment by thomasstjerne** [comment]
Frontend on dev now. But it seems that the union sector is placed one level to deep from the parent. When I drag "Not assigned phylum" from index fungorum onto Kingdom Fungi in assembly, there will be a placeholder "Not assigned phylum", but the sector sits in the descending "Not assigned class" 
![placeholderSector](https://user-images.githubusercontent.com/1666484/78357881-88ebba80-75b2-11ea-8760-ce3855b9a468.png)

**Comment by mdoering** [comment]
The target side is really difficult. The only sectorKey around could be deep below the actual attachment point...
