### ISSUE TITLE
Comments to a new version of Clearinghouse interface

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#522]
Tested at https://data.catalogue.life/ on 2020-03-27
Frontend version: e81f8b7 March 27, 2020 1:04 AMBackend version: ea703ba March 26, 2020 12:33 PM

**Comment by yroskov** [comment]
0. Bug: after 30 min my work with a new interface via Firefox 74.0 browser I have got blank screen. Reset, re-enter did not fix this bug. I switched to MS Edge and continued tests.
![image](https://user-images.githubusercontent.com/28574252/77795104-ff307000-703a-11ea-8c92-a4aed91e0a2e.png)

**Comment by yroskov** [comment]
Tests of **Catalogue** menu item
![image](https://user-images.githubusercontent.com/28574252/77795273-46b6fc00-703b-11ea-8aab-3629a50e36cf.png)

**Comment by yroskov** [comment]
**Source Databases:** 

- [ ] 1)	List of databases generates very slowly (21 sec) and do it every time when I leave/come back to this page.
- [ ] 2)	Please **add search box (Search Database) to this page** as it was done on Datasets page (in the  same location with the same functionality). I need to find database from the list in the Catalogue project.
- [ ] 3)	Please **add horizontal scroll bar** (table is too wide, and I cannot see all tables)
- [ ] 4)	Sorting does not work in columns
- [ ] 5)	Please **add Database ID** as a next column to database Title
- [ ] 6)	Species Count – incorrect title or incorrect implementation. Present counts show number of binomials (accepted + synonyms), but not a number of species. I need to see in the table: Number of accepted living species, Number of accepted extinct species, Number of accepted living trinomials, Number of accepted extinct trinomials, Number of synonyms (binomials +trinomials), Number of common names.
- [ ] 7)	It would be better to show counts for species, synonyms, common names, etc. separately from statistics on issues – in two (or more) different tables.

**Comment by yroskov** [comment]
Bug. When I click on one of banners in Tasks, interface says: Object doesn't support property or method 'flat'. The same bug for Duplicates

![image](https://user-images.githubusercontent.com/28574252/77795798-276c9e80-703c-11ea-9c4d-3a78f37ed227.png)

**Comment by mdoering** [comment]
@yroskov the pages have hardly changed. The _Source Databases_ view was some time ago called Issue Matrix. It is NOT supposed to be the dataset search.

> **Source Databases:**
> 
> * [ ]  1)	List of databases generates very slowly (21 sec) and do it every time when I leave/come back to this page.
yes, it needs to check all issues for all datasets which takes time.

> * [ ]  2)	Please **add search box (Search Database) to this page** as it was done on Datasets page (in the  same location with the same functionality). I need to find database from the list in the Catalogue project.
A new feature. Would you really want to check a single dataset?
In that case go to the dataset search and on a datasets issue page.
This page is supposed to give you an overview across ALL dataset issues.

> * [ ]  3)	Please **add horizontal scroll bar** (table is too wide, and I cannot see all tables)
just scroll to the left, you can do that already

> * [ ]  4)	Sorting does not work in columns
It works for me. Maybe a MS Explorer problem? Please try with Chrome which is the prime brower we work against. We will adjust to other browsers later

> * [ ]  5)	Please **add Database ID** as a next column to database Title
ok

> * [ ]  6)	Species Count – incorrect title or incorrect implementation. Present counts show number of binomials (accepted + synonyms), but not a number of species. I need to see in the table: Number of accepted living species, Number of accepted extinct species, Number of accepted living trinomials, Number of accepted extinct trinomials, Number of synonyms (binomials +trinomials), Number of common names.
please discuss this further on a dedicated [backend issue](https://github.com/CatalogueOfLife/backend/issues/668) as we cannot change these metrics retrospectively easily and its important we get these right.

> * [ ]  7)	It would be better to show counts for species, synonyms, common names, etc. separately from statistics on issues – in two (or more) different tables.

Agree. The single column for number of species was requested by me to get a rough indication on the size of the dataset and to be able to get an idea of the relative size of the problems. I.e. 80 issues on a small dataset are way more of a problem than 80 on a large one.

**Comment by mdoering** [comment]
@yroskov it would be good to have all your comments as individual issues in the future, so we can work on them individually. 

I cannot reproduce the last bug you mentioned when clicking on issue tabs or duplicates.
It all works fine on Chrome and Safari. Please don't use Explorer!

**Comment by thomasstjerne** [comment]
The source database select is now displayed always. Text says "select source" or if a source is selected "source <id>".

This should make navigation more smooth as you dont have to wait for all issues for all datasets
