### ISSUE TITLE
How to get from a name search to the workbench?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#526]
When you want to apply a decision on a name that you do not know the source of, how would you do that efficiently?

Naively I have searched for the name in the draft, e.g. [Neoaemula vector](https://data.catalogue.life/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Neoaemula%20vector&sortBy=taxonomic)

But how do you get from there to the workbench?
And should usage detail pages maybe also show decisions? The data model does not link decisions to the synced usages in the catalogue right now, but maybe it should

**Comment by mdoering** [comment]
At least the [taxon details page](https://data.catalogue.life/catalogue/3/taxon/17ff8f38-8589-4224-a775-29ee70c6d93c) should show and link to the sector the name came from.

**Comment by thomasstjerne** [comment]
Link now in the expanded row
