### ISSUE TITLE
Stop import button missing?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#532]
There's no stop button for datasets that are indexing, or maybe the stop button is just missing?

![image](https://user-images.githubusercontent.com/8573609/78189727-35556180-7438-11ea-99fa-d4d5ed8badd7.png)

Frontend version: 1eaaa21 March 30, 2020 7:54 AM
Backend version: e8c3f64 March 31, 2020 4:25 PM

**Comment by gdower** [comment]
Indexing is taking a really long time and I needed to update that dataset so that I can hopefully send it to ITIS tomorrow, so I just created a new dataset and will delete the other one:

![image](https://user-images.githubusercontent.com/8573609/78190536-ce38ac80-7439-11ea-9244-5c123d81f8e0.png)

**Comment by gdower** [comment]
Manually sending a `DEL //importer/2120` API call worked.

**Comment by mdoering** [comment]
cool, I guess its fine in this case to create a new dataset. But the idea is that datasets keep their identifier, so we should not delete them and switch. They should also keep their import/metrics history. For first experiments we should probably not use prod. In GBIF we usually have 3 environments. Prod, uat (user acceptance testing) and dev. dev is really for developers to make sure the code works, UAT is to stage new features and have a testing site that users can interact with. The IPT in dev mode connects to UAT. It is supposed to be stable, but data can be wiped now and then. 

We might want to also setup a UAT environment. I was hoping to get by without it, as the separation between dev and uat isnt always clear. and dev without data is largely the same as a local development. 

Should we try to use dev more for these kind of first tests on new datasets?

**Comment by gdower** [comment]
> Should we try to use dev more for these kind of first tests on new datasets?

That's been my usual approach, but if dev was broken, then I would try to use prod. Now I've got a local clearinghouse again, too, which also allows testing there.

**Comment by mdoering** [comment]
not anymore
