### ISSUE TITLE
Placeholder sector link wrong

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#534]
When a sector has a placeholder as a subject with a given placeholdeRank attribute, the link to the subject tree in the assembly should be constructed to be a placeholder, i.e. `{ID}--incertae-sedis--{RANK}`

https://data.dev.catalogue.life/dataset/31496/sectors?limit=500&offset=0

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/clearinghouse-ui/issues/518

**Comment by thomasstjerne** [comment]
Depends on https://github.com/CatalogueOfLife/backend/issues/677
