### ISSUE TITLE
Upload *.tree files with plain text content type

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#535]
I am using the suffix ´*.tree´ for text tree files.
Can the uploader in the UI post these files with content-type `text/plain` to the API?

**Comment by mdoering** [comment]
@thomasstjerne I would hope this is a simple change. Can we do this easily? It helps my testing quite a bit

**Comment by thomasstjerne** [comment]
Do you have a small example .tree file for testing?

**Comment by mdoering** [comment]
various ones in [trees.zip](https://github.com/CatalogueOfLife/clearinghouse-ui/files/4516034/trees.zip)
