### ISSUE TITLE
How to enter a tab character in dataset settings?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#536]
How can we add a single tab character as the CSV delimiter setting?
https://data.catalogue.life/dataset/1053/meta

Hitting tab goes to the next field, entering \t escapes the backslash so the JSON is `\\t` at the end.

**Comment by thomasstjerne** [comment]
I think it behaves correct. When I enter `\t` it posts "\\t" which will deserialize to "\t" - when it comes back from the server it is again correctly given as "\\t" which the UI deserializes and show as "\t".
https://data.dev.catalogue.life/dataset/31511/meta

**Comment by mdoering** [comment]
But that is not what we want! We need to enter a tab, not an escaped tab.
How can you do this? Im not saying that escaping \t to \\t is wrong. But "\t" is no delimiter we are ever interested in. A single tab char is very often needed. How do you enter that?

**Comment by thomasstjerne** [comment]
Ahh now I get it.
I thought you wanted the delimiter like it is given SQL, e.g.
`with delimiter E'\t'` or `enclosed by '\t'`

Maybe a little checkbox for tab delimited could do then. Even if the tab is captured by the input, it will be visually challenging when you scan the settings by eye

**Comment by mdoering** [comment]
Yes, that would work. Or allow entering escaped chars and do not escape them again. Basically show the escaped version and unescape them when passing into the API
