### ISSUE TITLE
Select project not listing managed datasets

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#537]
When selecting a new project for assembly the offered datasets are not all managed datasets. It seems to only list the ones that already have sectors. When starting a new project there is no way to create sectors. Use the regular dataset search to list all managed datasets as projects. We could require that an alias has to be present to qualify as a selectable project - then we can better identify them?

**Comment by thomasstjerne** [comment]
The list of projects is currently fetched like this:
`dataset?origin=managed&limit=1000`

This will of course change when users has a list of projects they can pick from.
