### ISSUE TITLE
Replacing a sector target deletes its entire parent

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#538]
When creating a new ATTACH sector under a target taxon that already has a taxon with the same subject name the UI offers to replace the existing duplicate in the target tree. But it actually deleted the attached parent with all its subtree!

To replay:
 - create newly managed dataset and upload the 
[animalia.txt](https://github.com/CatalogueOfLife/clearinghouse-ui/files/4443894/animalia.txt)
tree file
 - create new external dataset and upload the [trilobita.txt](https://github.com/CatalogueOfLife/clearinghouse-ui/files/4443895/trilobita.txt) file
 - go to the assembly of the managed dataset (you need to enter the dataset key into the URL manually, see #537)
 - create new sector from new trilobite source and drag class "Trilobita" to "Arthropoda" in the target. Select ATTACH and "replace"

**Comment by mdoering** [comment]
@thomasstjerne @yroskov @gdower this is important as it is very dangerous and could delete large parts of the tree in CoL in error!!!

**Comment by mdoering** [comment]
I think I simply misunderstood what replace does. It replaces the target taxon with the source one. In the case above when dragging Trilobita onto Trilobita it makes sense and works as expected.

Dragging it to a different, higher taxon like Arthropoda gave the warning "Trilobita already exists". Then the replace button felt to me it will replace that duplicate taxon.

Maybe we should only show the replace option when the same name exists in source and target?

**Comment by gdower** [comment]
At some point someone probably will accidentally badly damage the catalogue, which is why figuring out how to implement undo functionality ( #260) might be important though probably very difficult. If we keep the monthly (or twice a month) releases and can use a release as the basis for starting a new catalogue release, we could at least limit the extent of the damage by restoring the catalogue from the most recent release.

**Comment by mdoering** [comment]
yes thats an option. But we also do have continuous backups so in serious cases we can rebuild the entire Clearinghouse database from the backup and then copy over the complete CoL draft as it was at that stage. Quite some human labour involved, but in case of hopefully rare serious deletions we can surely restore

**Comment by thomasstjerne** [comment]
I ended up keeping the replace option only if Rank AND Taxon name are equal
