### ISSUE TITLE
Search in assembly is not properly expanding tree

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#539]
If you search for _Aspilota_ on dev in assembly on a fresh, unexpanded tree it doesn't expand the tree beyond Biota, but the nodes for the full classification hierarchy for _Aspilota_ below kingdom have an unexpanded minus next to them. It's only reproducible if you start with a fresh tree that is not expanded: https://data.dev.catalogue.life/catalogue/3/assembly 

In particular if Animalia is expanded, the tree sometimes expands correctly or at least partially expands.

Frontend version: c3c0841 April 6, 2020 8:33 AM
Backend version: 3e24708 April 5, 2020 12:23 PM

**Comment by thomasstjerne** [comment]
Actually, I think it works, it is just very slow when it is a deep search and taxa on the way down has many siblings. Try to do the above described and just wait, maybe 20-30 sec or even longer.
At some point I tried to have a spinner/loading indicator that was running while fetching from the backend and organising the tree, but it is tricky as most of the time is spent on rendering which I haven´t figured out how to apply hooks to.
