### ISSUE TITLE
Ant tables aligns filters in table headers right, makes them hard to find when columns are wide

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#544]
We should be able to filter the dataset search by origin

**Comment by thomasstjerne** [comment]
Was always possible:
<img width="417" alt="origin" src="https://user-images.githubusercontent.com/1666484/79453022-606bb380-7fe9-11ea-91c8-b7254330ffa8.png">

**Comment by mdoering** [comment]
Hm, not sure why I did not see that before. It definitely used to be there all the time ;)

**Comment by mdoering** [comment]
I think I know why I missed the origin filter. If you have a wider table with less columns the filter icon aligns with the next column to the right which is size. It does not appear to be related to origin:

<img width="1573" alt="Screenshot 2020-04-22 at 11 56 10" src="https://user-images.githubusercontent.com/327505/79968376-49690d80-8490-11ea-84ca-d829e37538cd.png">

**Comment by thomasstjerne** [comment]
https://3x.ant.design/components/table/

**Comment by mdoering** [comment]
If we carefully alternate column backgrounds with a very bright grey it becomes clear, like in the [ant table docs](https://3x.ant.design/components/table/#components-table-demo-head).

**Comment by thomasstjerne** [comment]
> If we carefully alternate column backgrounds with a very bright grey it becomes clear, like in the [ant table docs](https://3x.ant.design/components/table/#components-table-demo-head).

Actually, the dark grey indicates that this column is the sort column. If the sorting is removed, all headers have the same color.

Most table in the clearinghouse now calculates their width based in the number of displayed columns. This will in general solve this issue, however there could still corner cases when the user only has selected columns with very short values in the data
