### ISSUE TITLE
Add "show sector" to assembly context menu

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#548]
... and link to the datasets sector table view. Can we even filter out the very sector in that list?
It is the only place to see the target/subject and if its broken to rematch it

**Comment by thomasstjerne** [comment]
Could we have `key` (sectorKey) as param on the sector endpoint?
https://api.catalogue.life/sector?datasetKey=3&limit=100&offset=0&subjectDatasetKey=1028

**Comment by mdoering** [comment]
yes, but should we already plan for the new dataset scoped version of the URL? And should this be `id` instead of key or better `sectorKey` to be clear? 
https://api.catalogue.life/dataset/3/sector?subjectDatasetKey=1028&limit=100&offset=0

**Comment by mdoering** [comment]
I just see that the sector search already uses `id` for the subjectId.
It also offers a `targetId` parameter.

I would propose to rename `id` into `subjectId` and use `id` instead for the sector.id

**Comment by mdoering** [comment]
https://api.dev.catalogue.life/dataset/3/sector?subjectDatasetKey=1028

search by targetID
https://api.dev.catalogue.life/dataset/3/sector?targetId=7534bec7-b948-4f8c-aa02-b58d0de1f449

search by sectorKey, i.e. ID
https://api.dev.catalogue.life/dataset/3/sector?id=2686
