### ISSUE TITLE
import history extremely slow

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#550]
Not sure what it is, but when I click on import history of Orthoptera it takes a minute to show up:

https://data.catalogue.life/catalogue/3/dataset/1021/imports

The API call itself is quick:
https://api.catalogue.life/dataset/1021/import?limit=10

One of the imports has a huge error value though - could that be an issue?

**Comment by thomasstjerne** [comment]
Still the case? It loads in less than 1 sec here

**Comment by mdoering** [comment]
Yes, but it seems to be restricted to Safari. On Chrome it takes 1-2 seconds without doing any API calls, just the rendering itself is seemingly slow

**Comment by mdoering** [comment]
On Safari it never seems to render and the button freezes

**Comment by mdoering** [comment]
This is still an issue making the use of the import history impossible for some datasets.
E.g. ferns: https://data.catalogue.life/dataset/1140/imports

Maybe we can tackle this together with #457 and #598
