### ISSUE TITLE
Change dataset sectors page to dataset projects

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#552]
The Clearinghouse-wide sectors (or projects) interface seems to be showing sectors for all projects, but they all point at draft catalogue 3 instead of the release they are actually attached to. If you look at the links for the sectors they all point at project 3.

https://data.catalogue.life/dataset/1053/sectors?limit=500&offset=0

I think the same bug is on dev, but we don't have CoL releases on dev to check. I found this though which seems to point at the same project, too, even though there are probably 2 releases that the sectors should be pointing at:

https://data.dev.catalogue.life/dataset/31451/projects?limit=500&offset=0

**Comment by gdower** [comment]
It might also be a problem for the sync buttons, sync history, and probably logging.

**Comment by mdoering** [comment]
Yes, the sectors page for standalone datasets call for all sectors across any project and does not show to which project these belong on prod:
https://api.catalogue.life/sector?limit=500&offset=0&subjectDatasetKey=1053

On dev its the same. Dangerously you can even trigger a sync for all these sectors across various projects including releases. I will make sure any sync will immediately fail for releases.

On the menu reorganisation issue [we decided to list projects](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/531#issuecomment-611484077), not sectors for global datasets:

> add projects menu item for public datasets that lists all projects a dataset contributes to

It seems the new projects menu on dev still lists all sectors though, so this still needs to be implemented:
https://data.dev.catalogue.life/dataset/31451/projects?limit=500&offset=0

Btw, all links from those dataset title wrongly take you to the metadata page of the dataset you are already in. 

<img width="1301" alt="Screenshot 2020-04-17 at 23 00 54" src="https://user-images.githubusercontent.com/327505/79613968-d3ffe480-80ff-11ea-9cc0-791e30036176.png">

Instead this page should just list all projects that the dataset contributes to (and probably list each projects releases separately again). And then link each project to the full list of sectors. We could  just link to the respective project page for the sectors like here:

https://data.dev.catalogue.life/catalogue/31450/sector?limit=100&offset=0&subjectDatasetKey=31453

**Comment by mdoering** [comment]
I have created. dedicated issue for the [project page](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/641).
