### ISSUE TITLE
Add sectors interface back to datasets nested within project

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#553]
Could you please add the [sectors interface](https://data.catalogue.life/dataset/1053/sectors?limit=500&offset=0) back to the menu for dataset nested within project? It should be scoped to just the project though so that we can manage sectors for a dataset within a project (instead of seeing all the projects that the dataset contributes to).

**Comment by mdoering** [comment]
Is this really needed when you can filter the sectors to just one dataset in a project already?

https://data.catalogue.life/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=1010

(note there is a small [UI bug](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/555))

We should avoid to redundantly show the same things in various places, [the menu is already really large](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/531#issuecomment-615481686).

Project sectors are now hidden in the 3rd level of project details, so maybe thats why it's less intuitive. I am not a fan of the 3rd level anyways and would prefer to see the project details items to be raised again. Sectors, decisions & syncs at least to me are very dataset related and equally important to just the assembly tree. 

@thomasstjerne please lets discuss this first before implementing any changes
