### ISSUE TITLE
Add all dataset search filter params

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#566]
All dataset search parameters should be accessible through the URL at least. Input forms would be nice, but not really needed. Establishing links is the most important part. New ones missing are:

 - [ ] **private**: if true shows only private datasets (the the current user has access to), false only public ones
 - [ ] **releasedFrom**:Filters release datasets by their parent project.Automatically also restricts datasets to origin=released
 - [ ] **releasedFrom**: datasetkey of parent project
 - [ ]  **contributesTo**: Filters datasets to only list those that contribute as a source dataset with at least one sector to a given project.
 - [ ] **hasSourceDataset**: Filters datasets by having at least one sector with a given source datasetKey. Sectors only exist for managed but also released datasets.
 - [ ] **editor**: Filters datasets by having the given editor key authorized.
 - [ ] **modifiedBy**: Filters datasets by the user key that has last modified/created the dataset.

**Comment by mdoering** [comment]
Does it make sense to simply pass through all http params to the API without checks if they exist?

**Comment by thomasstjerne** [comment]
> Does it make sense to simply pass through all http params to the API without checks if they exist?

I think it does so already.

**Comment by mdoering** [comment]
Excellent. It indeed does: https://data.catalogue.life/dataset?limit=20&offset=0&releasedFrom=3
