### ISSUE TITLE
Copying/pasting scientific names

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#575]
Pretty much anywhere there is a scientific name in any user interface, it's really essential to be able to quickly copy (and paste) the scientific names. If people have to type in Latin names manually, they are inevitably going to make spelling mistakes. A lot of workflows depend on quickly getting the correct scientific name and it takes extra time to verify manually typed spellings, so it's really essential that we make it quick and easy to copy (and paste) scientific names.

In assembly, it's not possible to copy scientific names in both the assembly tree and the source data frame. [Click to copy works in some place like the uninomial column in workbench, but not in the scientificName column.](https://data.dev.catalogue.life/catalogue/3/dataset/1069/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0). There's other places like the [taxon](https://data.dev.catalogue.life/dataset/1069/taxon/1) pages where it's also hard to copy names because they are links.

**Comment by gdower** [comment]
Thanks so much for adding this in, @thomasstjerne! Being able to quickly copy names in assembly is fantastic. :+1:

**Comment by thomasstjerne** [comment]
👍
Added to headers on taxon pages as well btw
