### ISSUE TITLE
Save metadata in the Clearinghouse: Error 403

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#581]
@thomasstjerne @mdoering 
https://data.catalogue.life/catalogue/3/dataset/1011/meta
Frontend version: 5c746b5 April 30, 2020 7:30 AM
Backend version: f881331 April 27, 2020 4:05 PM

I have tried to safe FLOW metadata on prod after I changed date in Received by CoL field. I have got an error message 403.
 
![image](https://user-images.githubusercontent.com/28574252/80977912-02add880-8deb-11ea-83b4-f3888189bc6c.png)

I did refresh window in my browser; re-logged in. It did not resolve a problem.

**Comment by mdoering** [comment]
Thats the new security, you are not the editor of FLOW ;) 

Until we have the metadata patch & editor admin UI deployed on prod I'll make you an editor of all datasets in the range of 10-2000 so you can change all GSDs we currently have apart from some very new ones that I need to find out. But we should restrict access soon after to use the real world.

**Comment by yroskov** [comment]
Thanks! Now works.
