### ISSUE TITLE
Delete decision doesn't work in workbench

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#582]
@yroskov tried to delete decision 17302  by clicking the `x` next to update for the decision in the [workbench](https://data.catalogue.life/catalogue/3/dataset/1011/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0), which caused the `x` to disappear, but the decision is still there:

http://api.catalogue.life/dataset/3/decision/17302

![image](https://user-images.githubusercontent.com/8573609/81014864-402e5800-8e23-11ea-894e-7d0c92e84fb7.png)

**Comment by mdoering** [comment]
same for [Mus musculus](https://data.dev.catalogue.life/catalogue/31450/dataset/31451/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=mus&rank=species)

**Comment by thomasstjerne** [comment]
I think this is fixed on dev now, if not reopen
