### ISSUE TITLE
name search classification opens up all names

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#586]
is this intended? I am getting lost when all results are opened together. I preferred the old way of opening one by one

**Comment by thomasstjerne** [comment]
No, not intended. A side effect from the UI library update.

**Comment by thomasstjerne** [comment]
> No, not intended. A side effect from the UI library update.

That was actually not true. All rows in a table must have a unique key, for this I have relied on nameIndexId which seems to be gone?

Hence the key for all rows is "undefined" and all rows will open when when any expand button is clicked.

How do I best construct unique IDs from the data in the nameSearchResponse ?

**Comment by mdoering** [comment]
with the exception of bare names it is the usage.id property.
Bare names have no usage id, just a name.id which is unique for bare names
