### ISSUE TITLE
name relations on taxon page bogus

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#587]
https://data.dev.catalogue.life/dataset/1700/taxon/fake

A list of all kinds of relation types, but with no values:

<img width="1495" alt="Screenshot 2020-05-07 at 00 17 43" src="https://user-images.githubusercontent.com/327505/81233998-30b43800-8ff8-11ea-845c-20ebdb63f3ec.png">

The API lists exactly those 5 relations, but the relatedNameID is not resolved and shown:
https://api.dev.catalogue.life/dataset/1700/name/fake/relations

**Comment by thomasstjerne** [comment]
formattedName was replaced by labelHtml according to
https://github.com/CatalogueOfLife/clearinghouse-ui/issues/463#issuecomment-568047164

API still has formattedName in this case: https://api.dev.catalogue.life/dataset/1700/name/hybrid

**Comment by mdoering** [comment]
makes sense. We only changed the name usages to contain label and labelHtml.
I will do the same for all names then

**Comment by mdoering** [comment]
It is a bit different though, cause usages have a label and also a name which will then again have a label. I start to regret the strict separation of names and usages...

**Comment by mdoering** [comment]
the Tree API also exposes formattedName not label so far...

**Comment by mdoering** [comment]
do we actually need the non hrml label at all?
I would like to reduce data on API objects if possible and this is a candidate. 

Could we just have „label“ on usages and names and make that the marked up name?

**Comment by mdoering** [comment]
labelHtml did the trick
