### ISSUE TITLE
/newdataset blank page

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#590]
Probably related to #589 but newdataset is loading blank on dev:

https://data.dev.catalogue.life/newdataset

Maybe because of the 404 on https://api.dev.catalogue.life/vocab/datasetSettings?

Frontend version: 5c746b5 April 30, 2020 7:30 AM
Backend version: f881331 April 27, 2020 4:05 PM

**Comment by mdoering** [comment]
Ah, yes. I renamed the enumeration `datasetSettings` to just https://api.dev.catalogue.life/vocab/setting

**Comment by mdoering** [comment]
@thomasstjerne note also that importFrequency, dataFormat and dataAccess has been moved to settings!
