### ISSUE TITLE
Cannot create sectors

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#591]
On dev I cannot create new sectors in the assembly tree:
https://data.dev.catalogue.life/catalogue/31552/assembly?assemblyTaxonKey=18&datasetKey=31501&sourceTaxonKey=2

The UI does not even try to call the API or open a modal window

**Comment by thomasstjerne** [comment]
Dependent on https://github.com/ant-design/ant-design/issues/24062

Pull request here: https://github.com/react-component/tree/pull/327

**Comment by mdoering** [comment]
Bleeding edge. Thanks!

**Comment by mdoering** [comment]
The "cancel" button does not work if you want to abort the creation of a new sector
