### ISSUE TITLE
Classification tree not opening to sourceTaxonKey

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#597]
In the classification tree on dev, the tree doesn't reopen to the sourceTaxonKey. To reproduce click below and it only opens to Arthropoda:

https://data.dev.catalogue.life/dataset/1029/classification?sourceTaxonKey=x9Q4

It should open to here:

![image](https://user-images.githubusercontent.com/8573609/81719443-b134c780-9442-11ea-9139-d18eaa328c89.png)

If someone uses a species taxon ID for the sourceTaxonKey, ideally it would open to that species as well.

Frontend version: 4ab1cf7 May 12, 2020 8:44 AM
Backend version: 4b267d3 May 12, 2020 7:03 AM

**Comment by mdoering** [comment]
Hm, why sourceDatasetKey? taxonKey seems to work and is the parameter I would have expected:

https://data.dev.catalogue.life/dataset/1029/classification?taxonKey=x9Q4

**Comment by gdower** [comment]
When navigating the classification tree `sourceTaxonKey` is added to the URL instead of `taxonKey`.

**Comment by thomasstjerne** [comment]
Where did you navigate from?

**Comment by gdower** [comment]
I probably navigated directly to /dataset/{key}/classification. If you expand any branch, you'll see sourceTaxonKey added to the URL instead of taxonKey:

https://data.dev.catalogue.life/dataset/1029/classification
