### ISSUE TITLE
Show more import history details

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#598]
When understanding failed and successful imports it is important to know details about the import. Please render all import attempt properties in the imports/metrics section:

 - "state": "failed"
 - "started": "2020-05-13T15:45:50.925919",
 - "finished": "2020-05-13T15:49:18.282546",
 - "createdBy": 103 (resolve user name)
 - "format": archive format for both uploads and external access
 - "downloadUri" (only for external access)
 - "upload": true (if true indicates it was a manual upload, no downloadUri in that case)

See https://api.catalogue.life/dataset/2128/import/3
and https://data.catalogue.life/dataset/2128/imports/3

See also #457 for a small change to the import history visualisation

**Comment by thomasstjerne** [comment]
Added to the very bottom of the page as this would only make little sense to external users.
