### ISSUE TITLE
Select source menu won't select new datasets

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#600]
If you register a new dataset and then try to get to the new dataset in workbench, you can't select the new dataset in the source even after registering a sector. To get around it you have to select another dataset in the select source menu, and then use the magnifying class to find the new dataset again.

![image](https://user-images.githubusercontent.com/8573609/82086780-a41f0f00-96b4-11ea-8eac-5689d70264e4.png)

**Comment by gdower** [comment]
Frontend version: d2d0a59 May 13, 2020 8:46 AM
Backend version: b38b74b May 12, 2020 10:11 AM

**Comment by gdower** [comment]
(I didn't try to assemble this example test dataset, but @yroskov hit the same issue with Collembola 2130 even after assembling it.)

**Comment by mdoering** [comment]
very related to this issue: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/541

**Comment by mdoering** [comment]
it seems the source list is cached, so it doesnt update when underlying data changes
