### ISSUE TITLE
Infinite loop when using LR dataset IDs

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#605]
Everything looks okay if you use the [latest release dataset IDs](https://data.catalogue.life/dataset/3LR/names), but in the background the Clearinghouse goes into an infinite loop of requesting the dataset over and over again:

GET https://api.catalogue.life/dataset/3LR

**Comment by mdoering** [comment]
the UI was not (yet) designed to handle the latest release dataset keys.
As the regular dataset keys are integers it will surely break stuff if you use 3LR in the UI. I am surprised it works at all

**Comment by gdower** [comment]
My primary concern with it is that it's a fast rate of API requests and the clearinghouse otherwise behaves normally, so there's potential for DDoS and wasting the user's data plan.

**Comment by mdoering** [comment]
Agree. The UI should either treat these LR keys properly or simply reject non integer keys all together
