### ISSUE TITLE
I was not able to apply decisions for Tasks: Error 404

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#613]
Frontend version: 0e742b8 May 19, 2020 6:24 AMBackend version: 8e44f6c May 21, 2020 1:23 AM
on prod

I have tried to apply decisions for Tasks, and got Error 404 for all lines:

![image](https://user-images.githubusercontent.com/28574252/82576036-e29e4900-9b4e-11ea-8061-29eddba369ea.png)

**Comment by gdower** [comment]
It's maybe this [line](https://github.com/CatalogueOfLife/clearinghouse-ui/blob/2dec7119f75c34f3672eb2a824108f9dd31c2741/src/pages/Duplicates/index.js#L338).

**Comment by yroskov** [comment]
@thomasstjerne @mdoering 
![image](https://user-images.githubusercontent.com/28574252/83525281-5d9a2480-a4aa-11ea-9087-0b60c5aa8f91.png)
