### ISSUE TITLE
Show name status in context of code

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#617]
The nomenclatural status vocab is code agnostic and uses a BioCode based terminology not familiar to users of the botanical or zoological code.

Instead of showing the name status directly use the [provided vocabulary labels for the zoological and botanical code](http://api.catalogue.life/vocab/nomstatus)

E.g. instead of 
> Code: botanical
> Nomenclatural Status: unacceptable
https://data.catalogue.life/dataset/2123/name/95538509-2c87-4d30-babf-a390b30084aa

Render:
> Code: botanical
> Nomenclatural Status: nomen illegitimum

The botanical label should be used for various codes ( BOTANICAL, BACTERIAL, CULTIVARS, VIRUS). If no code is given we could use the status terms as they are

**Comment by thomasstjerne** [comment]
Closed in UI, but awaits https://github.com/CatalogueOfLife/backend/issues/873
