### ISSUE TITLE
Decision name search

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#628]
The decision table combines a proper search with forms above the table and searchable columns like subject name and dataset title:

https://data.catalogue.life/catalogue/3/decision?broken=true&limit=100&mode=block&offset=0&subjectDatasetKey=2073

I have implemented a new `name` parameter in the decision API so we can actually search on subject names properly (the current implementation seems to only search on the current page which is not very useful).

Please replace the forms to use the new `name` parameter and remove the dataset title search as it exists already as a proper search form. 

If space is limited I am happy to keep the search icon and form on the table header, but it should propagate to the API instead of doing a client search.

**Comment by thomasstjerne** [comment]
The is name parameter is already used, but powered by an autosuggest. Would it be better to have a simple text input without suggestion?

**Comment by mdoering** [comment]
Yes, please do not use suggest but make this a free text field.
It is important to look for broken decisions which are likely to not have any matching name record. Also the search allows to search for any parts of the name, so it does not have to be a full name at all

**Comment by mdoering** [comment]
the same applies for sectors
