### ISSUE TITLE
Replace dataset settings with Options menu

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#638]
The public dataset pages should have an Options page instead of a settings page just as we do for projects: https://data.dev.catalogue.life/dataset/1700/settings

Options, no matter if on a project or dataset, [should only be visible to editor and admin users](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/621).
The available actions should depend on a datasets origin:

ALL:
 - export

MANAGED:
 - release

And if the user is an ADMIN user there should also be the action:
 - reindex (formerly in admin page)

All other sync and rematch actions are already present on the respective project pages and we should avoid duplicating them in several places

**Comment by mdoering** [comment]
The global and project dataset Options page should differ slightly, so that project options have additional actions:

**Global Dataset Options**:
 - manage settings
 - actions
   - reindex
   - export in different formats (AC portal, ColDP, DwC Simple, DwC-A, BibTex)
   - delete orphaned names
   - delete orphaned references

**Project Options**:
same as Global Dataset Options but in addition also have
 - actions
   - release
   - recalc sector counts

**Comment by thomasstjerne** [comment]
Do we have API for:
- delete orphaned names
- delete orphaned references
- recalc sector counts

And is there away to tell which format the export should be?

**Comment by mdoering** [comment]
So far we only have one export format. But there will be some coming, so I thought the UI might already be preparing for that by offering a selection
