### ISSUE TITLE
Cannot find taxon in assembly source frame search

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#651]
In assembly, when using search within source dataset, there's no way to get back to the full source dataset without doing a page reload. Probably most people would expect that when you hit the `ⓧ` (see the mouse cursor `☝️` in the screenshot below) on the source frame search term that it would reload the source dataset frame so that the full source dataset can be viewed again.

![image](https://user-images.githubusercontent.com/8573609/84923596-06d94100-b08d-11ea-8945-c39619888979.png)

Instead it just clears the search term, and the source frame is still stuck on the search results:

![image](https://user-images.githubusercontent.com/8573609/84923803-4dc73680-b08d-11ea-936a-9636fd922df1.png)

Expected behavior after clicking `ⓧ` (showing the full source dataset):

![image](https://user-images.githubusercontent.com/8573609/84924746-9d5a3200-b08e-11ea-8c2c-c9ce3cad5d75.png)

Hopefully this will be a tiny fix with just needing to trigger a source frame reload of the source dataset when the search within source dataset `ⓧ` is clicked.

Frontend version: c99dba2 June 17, 2020 9:47 AM
Backend version: 507800e June 17, 2020 8:53 AM

**Comment by mdoering** [comment]
@thomasstjerne this is the issue we just demo'ed

**Comment by thomasstjerne** [comment]
Basically when the UI seeks to drill down to a target taxon, it calls the classification of that taxon and builds the tree from the bottom and up. On the way up it fetches siblings of each taxon through their parents using the /children endpoint. In the case of several roots, the "sibling" roots would not be fetched as they are orphants. 
Now it fetches all the root taxa from another endpoint and splices the great great  ..... .... great grand parent into the set of roots after the bottom up fetching.
