### ISSUE TITLE
Broken classification links in workbench

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#653]
The classification links on [this page](https://data.catalogue.life/catalogue/3/dataset/1140/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0) are broken because they have an undefined variable:

https://data.catalogue.life/catalogue/3/dataset/1140/undefined/taxon/x8

**Comment by mdoering** [comment]
Hm, they all work for me. Logged in and anonymous also.

**Comment by gdower** [comment]
It's still not working for me on Firefox 76.0.1 (64-bit) or Google Chrome 83.0.4103.106 (Official Build) (64-bit). Did you click the classification links:

![image](https://user-images.githubusercontent.com/8573609/85067114-c6a1bd80-b175-11ea-9f8a-c21d568d396c.png)

**Comment by mdoering** [comment]
Ahhh, yes. I didnt see these links as they were far to the right.
broken indeed
