### ISSUE TITLE
Blank page when doing union join in assembly

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#655]
As demoed on the call, when doing a union join on a manually added taxon in assembly, sometimes the whole page goes blank. I forgot to save the stacktrace before exiting Zoom, and I cannot reproduce it again because 90% of the time, the union join actually works right. I think it may be caused by some other issue than just union joining onto a manually added, empty taxon.

Olaf might have the stacktrace in the chat log for the meeting. Otherwise, I'll log the stacktrace here the next time I see it happen.

**Comment by thomasstjerne** [comment]
I cant reproduce this and there has been some bug fixing in the trees that could be the reason for this.
Please reopen if this happens again
