### ISSUE TITLE
Cannot find taxon ec2087d7-4f7e-45ac-8de7-670c157b96fc in tree 😥

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#656]
As demoed in the call, after adding the 2nd sector in Lycopodiopsida, an error appears that taxon `ec2087d7-4f7e-45ac-8de7-670c157b96fc` cannot be found, which is reproducible:

![image](https://user-images.githubusercontent.com/8573609/85753635-0a467b00-b6d2-11ea-9fe9-182b86a41f71.png)

The ID `ec2087d7-4f7e-45ac-8de7-670c157b96fc` is in the URL as the assemblyTaxonKey. The taxon does actually exist: 

http://api.catalogue.life/dataset/2152/taxon/ec2087d7-4f7e-45ac-8de7-670c157b96fc

There was only one API call with a 404 error in the network console and that was for the 2152 logo, so I think the taxon did exist.

I tried adding the 3rd group after dismissing the error message, and it did not return. However, the source frame is showing a circle exclamation indicator with the message that the taxon doesn't exist:

![image](https://user-images.githubusercontent.com/8573609/85755315-737abe00-b6d3-11ea-91a3-ae5f0a7d0f2f.png)

**Comment by thomasstjerne** [comment]
Did you use the "REPLACE" mode?
If so, I think this is fixed now (was reported here as well: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/660)

**Comment by thomasstjerne** [comment]
I think its fixed now, please reopen if you can still reproduce
