### ISSUE TITLE
Show sector details

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#658]
A sectors subject or target can have various properties that we do not show in the sector UI:

- id
- name
- authorship
- rank
- status
- parent

If there are sectors for the same name it becomes confusing as you cannot tell which is which:
https://data.catalogue.life/catalogue/3/sector?limit=100&name=Cheilanthes&offset=0

I think we used to show the raw JSON underneath each sector. That is an easy remedy of the problem.
Other ideas welcome!

There are more [sector properties](https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/model/Sector.java#L23) that are not shown currently and some of [which we also need to be able to edit](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/547):
 - code
 - placeholderRank
 - ranks
 - entities
 - note

The following properties should not be editable: subjectDatasetKey, originalSubjectId, syncAttempt, datasetImportAttempt

**Comment by mdoering** [comment]
See also #523 and #547

**Comment by mdoering** [comment]
https://api.catalogue.life/dataset/3/sector?limit=100&name=Cheilanthes&offset=0

**Comment by gdower** [comment]
It would be really good to show the sector IDs in the UI, which will make it easier to work with the API when needed. I had been meaning to open an issue on that. :+1:

For example, in assembly here there are [2 different nested sectors](https://data.catalogue.life/catalogue/3/sector?limit=100&name=Doryopteris&offset=0) merging the genus [_Doryopteris_](https://data.catalogue.life/catalogue/2145/assembly?assemblyTaxonKey=629558e8-1dac-48ef-ad73-ba7956355ca6) back together, but in the UI it looks like there is only 1 sector. I don't think the sector colors need to be different, but at least showing the sector ID in the pop-up would help distinguish which sector a record came from:

[![image](https://user-images.githubusercontent.com/8573609/86149596-caacd400-bac1-11ea-977f-4be62203e2ca.png)](https://data.catalogue.life/catalogue/2145/assembly?assemblyTaxonKey=629558e8-1dac-48ef-ad73-ba7956355ca6)

**Comment by mdoering** [comment]
You can edit code, ranks & entities in the assembly tree, but not in the sector list view.

<img width="1180" alt="Screenshot 2020-07-17 at 12 07 46" src="https://user-images.githubusercontent.com/327505/87775343-3adb8980-c826-11ea-8295-98afca398fc8.png">
