### ISSUE TITLE
Some dataset options cannot be nullified

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#665]
Once they are set, it is not possible to nullify the project/dataset options, because there is no empty option in the menus:

- distribution gazetteer
- nomenclatural code
- data format
- import frequency

![image](https://user-images.githubusercontent.com/8573609/86814401-fa6e5580-c046-11ea-84c6-f1f19b392a3f.png)

This might need an API chnage because the API doesn't seem to allow unsetting these options either:

https://github.com/CatalogueOfLife/backend/issues/779

**Comment by mdoering** [comment]
API allows to unset an option be either leaving out the key alltogether or setting the key to json `null`
