### ISSUE TITLE
Sub-sector tags not shown in source frame for searched taxa

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/clearinghouse-ui#668]
Unless you have a better term, I'm calling the sector tags below a sector, a "sub-sector tag." For example, the WTaxa brown tag next to the genus _Periteloneus_ is a "sub-sector tag:"

![image](https://user-images.githubusercontent.com/8573609/87069136-4bfc1900-c1dc-11ea-87ba-3d3d7b1e57f7.png)

When searching for the genus _Periteloneus_, the WTaxa sub-sector tag does not show, which means that the taxon cannot be blocked because the action menu is inaccessible:

![image](https://user-images.githubusercontent.com/8573609/87068333-0559ef00-c1db-11ea-8e87-6f5f33600e95.png)

We can still block the duplicate genera by manually navigating through the source tree:

![image](https://user-images.githubusercontent.com/8573609/87067772-1e15d500-c1da-11ea-9e28-c9207a39f251.png)

I really like the new scrolling interface! :+1:

**Comment by thomasstjerne** [comment]
Note to self: This happens for taxa that is inserted on top of the first page (Those that otherwise would not be accessible as they would be on one of the following pages). In that case the copy of the parent nodes sector key fails
