### ISSUE TITLE
Comment to a new Assembly Tree look: missing authorstrings

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#670]
@thomasstjerne 
New tree look is much faster and better. Thanks!

The only problem, taxa in both Assembly Tree and GSD Tree have no authorstrings. As results, I do not know, which Cheilanthes or Doryopteris I need to union. 

![image](https://user-images.githubusercontent.com/28574252/87088654-c89df000-c1fa-11ea-9e38-8f0a586558ff.png)
 
**Could you pls bring back authorstrings in the trees.**

**Comment by gdower** [comment]
It's probably just using the name field instead of the labelHtml field:

https://api.catalogue.life/dataset/3/tree/0748be29-0e94-4f0b-922c-d09c27a09baa/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=3&type=CATALOGUE
