### ISSUE TITLE
Provide project wide sector defaults

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#673]
Sectors have 3 important properties that define how they sync: code, ranks and entities. 
Most of these are the same for an entire project. Allow to define them in project settings and apply them as defaults when creating new sectors.

As a quick start we should at least provide `distribution`, `vernacular` & `reference` as the default for new sectors to avoid https://github.com/CatalogueOfLife/backend/issues/787

**Comment by thomasstjerne** [comment]
If the relevant fields are included here: http://api.catalogue.life/vocab/setting
they should show up automatically.
But as ranks and entities can have multiple values, I suggest indicating that in the API:

````
{
"origin": [
"managed"
],
"name": "Sector entities",
"type": "EntityType",
"multiple": true
},
{
"origin": [
"managed"
],
"name": "Sector nomenclatural code",
"type": "NomCode"
},
{
"origin": [
"managed"
],
"name": "Sector ranks",
"type": "Rank",
"multiple": true
}
````

**Comment by mdoering** [comment]
It is not a setting stored in the backend. I was thinking of a UI project setting that gets applied in the UI whenever the UI posts a new sector

**Comment by mdoering** [comment]
If we add these settings would it be simple for the UI to pick them up when posting new sectors?
Checking settings in the backend for each request is not great. And caching them has all kinds of other problems and makes it quite complex

**Comment by mdoering** [comment]
Or we remove the setting from sectors and only configure it at the project level. But that would mean we treat all sectors and sources the same which might not be desired.

**Comment by thomasstjerne** [comment]
It would not be easy, but doable. There are quite a few place where sectors are edited / posted. 
We should still persist them in dataset settings right? (The UI doesn´t have any place to store them apart from localStorage which would be inconsistent across browsers / users)
Then the UI should fetch the dataset settings and apply relevant settings before posting / putting

**Comment by mdoering** [comment]
I think we don't really need this to happen on the UI level. I will add the dataset settings incl the multiple indicator (can the UI handle this already?) and then will use the defaults when a sync is triggered and nothing is set on the sector explicitly

**Comment by thomasstjerne** [comment]
I just pushed an adjustment to handle the multiple flag and injected the EntityType and Rank enums into the the form.
I think it should work on dev once the the settings show up in the `/vocab/setting` endpoint

**Comment by mdoering** [comment]
vocab endpoint changed to include multiple property: https://api.dev.catalogue.life/vocab/setting
The settings show, but the form does not render any sector_entity form
