### ISSUE TITLE
Separate source dataset & source metrics???

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#682]
The source dataset matrix table now combines metrics from the project (the first count columns are from sector sync metrics, ie. records that have been copied into the project already) with issue stats for the entire source dataset outside the project (these are the dataset import metrics for the entire source dataset).

It might be confusing to see drastic different numbers.
Would it be better to separate the 2 views into separate pages?
 - Source Datasets: show just the dataset import metrics with issues
 - Source Metrics: show the new source dataset metrics which are based on sector syncs for the project and allow a comparison with a previous release.

**Comment by thomasstjerne** [comment]
@mdoering in which of the two would we show the number of broken decisions?

**Comment by mdoering** [comment]
good question. Fits on both. But I would show it probably with the issues, so the first
