### ISSUE TITLE
Can we remove dataset contributesTo?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#687]
The dataset object has a contributesTo field that lists all dataset keys that have sectors which make use of it.
AFAIK this is only used in the dataset search to filter source datasets for a certain project or release.

As we now also have the source dataset matrix page in projects and releases is this still really needed?
It seems not to scale in the UI with more projects and releases coming:

<img width="1721" alt="Screenshot 2020-08-19 at 10 34 20" src="https://user-images.githubusercontent.com/327505/90612148-f027a580-e207-11ea-967e-e9965c918242.png">

It is also complicating the SQL in the backend quite a bit.
I would be glad if we can remove it.

On a dataset details page we should still show all projects and releases which make use of the dataset as a source for a sector. But that can be done more easily by calling `/dataset/{datasetKey}/source` which lists all source datasets.

**Comment by mdoering** [comment]
@thomasstjerne @yroskov @gdower Opinions on this?

**Comment by thomasstjerne** [comment]
It is used for the source select in the project menu section

**Comment by thomasstjerne** [comment]
> As we now also have the source dataset matrix page in projects and releases is this still really needed?

It is actually also used on that page

**Comment by thomasstjerne** [comment]
Ahh, we can remove it from the dataset object, the query param contributeTo is still needed

**Comment by gdower** [comment]
Do you mean only removing the contributesTo column from the dataset search results table in your screenshot above? I think that would be okay, although it might be useful to be able to filter on contributesTo with a search contributesTo box to make it easier to find the right dataset in cases where duplicates might get brought in by GBIF sync.

contributesTo on the [projects](https://data.catalogue.life/dataset/1193/projects) page of a dataset has definitely been very useful in catching problems.

**Comment by mdoering** [comment]
I mean to remove it from the object and therefore rendering of the dataset table. We might see hundreds of values at some point. I would definitely keep it as a search parameter

**Comment by thomasstjerne** [comment]
I´m good with that.

**Comment by mdoering** [comment]
@gdower the projects page you linked is listing sectors, but it should really be listing projects and optionally also releases.
But that does not need Dataset.contributesTo.

ok, then Ill remove it from the dataset object and @thomasstjerne would have to remove that column in the dataset table

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/4ddcb9306b0aeb53ab6b3eb7e598f5566038a8ad
