### ISSUE TITLE
How to active the assembly tree sector menu?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#693]
I cannot find a way to get the context menu in the assembly sector tree on dev.
right click, ctrl/shift click all dont work.

A but or an OSX pain?

**Comment by thomasstjerne** [comment]
Hmm. I use the trackpad on my mac and the usual two-finger click reveals it.

**Comment by mdoering** [comment]
works for me now too. dunno what that was, ignore
