### ISSUE TITLE
Broken sectors not marked

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#694]
Broken sectors are not marked in the UI on dev, but search finds them:

<img width="1514" alt="Screenshot 2020-08-21 at 22 05 34" src="https://user-images.githubusercontent.com/327505/90930250-8cb19980-e3fa-11ea-9a10-46d3b3b53a0b.png">

**Comment by thomasstjerne** [comment]
The UI only marks them if either the target or subject has no ID (i.e. a qualified guess). Theres currently no way to tell from the data that the sector is broken - maybe the api response could include a `broken: true` flag ?

**Comment by mdoering** [comment]
True, that becomes complicated. Should all returned sectors try to join to the current data and add a broken flag for both target and subject? Then we dont need to fiddle with the id.
