### ISSUE TITLE
Sector sync show no actions

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#696]
The action column in a projects sector sync is empty:

<img width="1767" alt="Screenshot 2020-08-21 at 22 27 22" src="https://user-images.githubusercontent.com/327505/90931727-84a72900-e3fd-11ea-94a3-577b3029298b.png">

Guess this should have rematch or sync depending whether the sector is broken?
See also #694

**Comment by thomasstjerne** [comment]
`type` attr was renamed to `job` in the API
