### ISSUE TITLE
why is no sector root shown?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#702]
In the assembly tree the "White Flies" sector is mentioned cause the tree API responds with usages that have sectorKey=2:

<img width="630" alt="Screenshot 2020-08-26 at 18 59 05" src="https://user-images.githubusercontent.com/327505/91333920-893d5a00-e7ce-11ea-9823-38ff6cdb9627.png">

But why is there no sector root with the triangle to select the menu from?
Is it because the parent taxa are all incertae sedis?

**Comment by thomasstjerne** [comment]
The UI determines if it is a sector root based on node.taxon.id = sector.taget.id 
Obviously, this fails for placeholder nodes. Initially I thought that adding a parentId to placeholder nodes would be enough, but @mdoering points out that there could be several placeholders in the node ancestry.

We need a way to determine if the sectorKey on a placeholder node is the root of the sector.

**Comment by mdoering** [comment]
What about comparing the sectorKey of a node with the sectorKey of its parent? If they differ we have a root. 
The TreeAPI could even set a "sectorRoot=true" flag, maybe thats useful?
