### ISSUE TITLE
Adapt to changed suggest type parameter

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#711]
boolean prefix flag is replaced by a `type` parameter with one of
 - PREFIX
 - WHOLE_WORDS
 - EXACT

it defaults to WHOLE_WORDS
See https://github.com/CatalogueOfLife/backend/issues/811

**Comment by thomasstjerne** [comment]
Is the backend deployed to prod yet?

getting 
Request failed with status code 500
There was an error processing your request. It has been logged (ID e50155367524d5c7).

But works on dev

**Comment by mdoering** [comment]
I though so, let me check

**Comment by mdoering** [comment]
elastic searhc problem, `life.catalogue.es.EsException: all shards failed`

**Comment by mdoering** [comment]
```
life.catalogue.es.EsException: all shards failed
	at life.catalogue.es.EsUtil.executeRequest(EsUtil.java:392)
	at life.catalogue.es.nu.NameUsageQueryService.executeSearchRequest(NameUsageQueryService.java:88)
```

`GET /dataset/3/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=test&sortBy=taxonomic&type=EXACT`

**Comment by mdoering** [comment]
maybe we need to switch to the new index. It is nearly done:
> Indexed 280/285 dataset 3

only 5 to go

**Comment by mdoering** [comment]
swapped the index and removed old one

**Comment by mdoering** [comment]
and API works!
