### ISSUE TITLE
Add extinct filter to name search

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#719]
with facet counts

**Comment by mdoering** [comment]
As data for living taxa is difficult as we only really see explicit marking of extinct taxa, I would prefer to make the extinct filter a simple boolean toggle. Either include extinct taxa or not, but leave all others always in, i.e. pass the extinct=true parameter to the API or not pass the parameter. See https://github.com/CatalogueOfLife/backend/issues/870

**Comment by mdoering** [comment]
Can we just make this a small toggle with the label `extinct`?
I dont think we need to mention the opposite living and extinct. The functionality is just inclusion of extinct taxa or not.

**Comment by thomasstjerne** [comment]
> Can we just make this a small toggle with the label `extinct`?
> I dont think we need to mention the opposite living and extinct. The functionality is just inclusion of extinct taxa or not.

done
