### ISSUE TITLE
Table rendering bug in Issues

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#726]
Frontend version: 02e1339 September 24, 2020 9:11 AMBackend version: 8b37897 September 24, 2020 4:27 AM

Testing World Plants aka "WP dev" on prod...

I have meet a problem with data presentation in the Issues report for Parent Name Mismatch:
https://data.catalogue.life/dataset/2209/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=parent%20name%20mismatch

The report indicates 107 results arranged in 3 pages. Going from page 1 to 2 and 3, I have spot inconsistency in data.

Go to Page 1 directly from the issue link Parent Name Mismatch. 
Short list of names.
 
![image](https://user-images.githubusercontent.com/28574252/94282885-fbac7180-ff15-11ea-83aa-f108263fece4.png)

Go to Page 2. Long list of names
Name _Aetheorrhiza bulbosa_ is in a first line again

![image](https://user-images.githubusercontent.com/28574252/94288647-42519a00-ff1d-11ea-97a3-0cf8561bf370.png)

Go to Page 3. Short list (it would be OK).
Name _Aetheorrhiza bulbosa_ is in a first line again. Plus other names from page 2 repeated on page 3 again (for example,
Commidendrum robustum, Commidendrum rotundifolium, etc.) 

![image](https://user-images.githubusercontent.com/28574252/94288928-a07e7d00-ff1d-11ea-88ff-0e9f27fd38fe.png)

**Comment by mdoering** [comment]
I can confirm the paging is wrong. The first 2 pages should show 50 records each, but the very first one one shows 10.
if you page forward and then back again its 50.

Also the ordering is wrong if you select ordering by name it should be strictly alphabetical, which works fine in the API:

needs auth cause its private:
> curl -s --user user:pass "https://api.catalogue.life/dataset/2209/nameusage/search?issue=parent%20name%20mismatch&limit=50&offset=0&sortBy=name" | jq ".result[].usage.label"

**Comment by yroskov** [comment]
Now I go back to page 1. Long list, and it is not identical to previous view of page 1.

![image](https://user-images.githubusercontent.com/28574252/94289472-61046080-ff1e-11ea-955d-e6dc164619e2.png)

**Comment by yroskov** [comment]
Hmm, I would say it is misapplication of term "ChecklistBank". For me, **ChecklistBank** is a warehouse with set of different source datasets and projects. Whereas, **Clearinghouse** is a tool for managing these data and project.

**Comment by yroskov** [comment]
Another feature in report rendering: some names repeated twice in the list like this: 
![image](https://user-images.githubusercontent.com/28574252/94296200-1687e180-ff28-11ea-9c1c-cb2abe21740d.png)
