### ISSUE TITLE
Frontend user roles

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#96]
Consider that the frontend should serve different roles:

 - anonymous user
 - authenticated used
 - dataset provider
 - CoL editor
 - pCat editor
 - system admin

What different views / actions are needed for these? It would be good to keep role specific parts deactivated to not overload the UI

**Comment by thomasstjerne** [comment]
After the recent user management update, menu items buttons etc can be shown/hidden based on an array of roles

Example: Right now, we only show assembly and dataset/ColSource sections to role="editor"
and import buttons are shown to roles=admin and editor only

If we are extending and renaming the roles (e.g. splitting the editor role), it would be good to do it soon so at least the default roles will not be renamed again

**Comment by mdoering** [comment]
I think it might be best to distinguish between the Col and pCat editor role. They will like to see different views, e.g. the ColSource is of no interest to the pCat editor. They will look at different datasets. [Currently we have](http://api.col.plus/vocab/coluser$role):
 - user (=authenticated user & dataset provider)
 - editor (=col+pcat editor)
 - admin (system admin)

I am not sure if we need to split these into the above 5 roles or if the user object should have properties that tell you if it's also a dataset provider or catalogue editor. Because for both catalogue editors and dataset providers you will need to know which catalogue and dataset(s) it is they are authorised for. Is it maybe best to keep the roles small, stick with the current 3 and deal with fine grained authorisation and view management on other user object properties (to be done)?

The dataset provider will be interested in seeing "review queues" for his dataset(s). Not sure if we should expose them to everyone. At least editing these should be restricted.

**Comment by mdoering** [comment]
superceded by https://github.com/CatalogueOfLife/backend/issues/580

**Comment by mdoering** [comment]
and #493 and #439
